# Generated by Django 5.1.1 on 2024-10-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='featured_product_id',
            field=models.IntegerField(null=True),
        ),
    ]
